spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.auto-offset-reset=earliest
spring.main.banner-mode=off
logging.level.root=warn
logging.level.com.howtodoinjava=info
logging.pattern.console=%-24thread %msg%n
